In [1]:
import numpy as np

In [6]:
def initialize():
    inp = 5
    h1 = 3
    h2 = 2
    h3 = 3
    out = 1
    
    w1 = np.random.randn(inp,h1)
    b1 = np.random.randn(1,h1)
    
    w2 = np.random.randn(h1,h2)
    b2 = np.random.randn(1,h2)
    
    w3 = np.random.randn(h2,h3)
    b3 = np.random.randn(1,h3)
    
    w_out = np.random.randn(h3,out)
    b_out = np.random.randn(1,out)
    
    print("Neural Network Architecture:")
    print(f"Input layer: {inp} nodes")
    print(f"Hidden layer 1: {h1} nodes")
    print(f"Hidden layer 2: {h2} nodes")
    print(f"Hidden layer 3: {h3} nodes")
    print(f"Output layer: {out} node")
    
    print("\nWeights and Biases:")
    print("Layer 1 - Weights:", w1)
    print("Layer 1 - Biases:", b1)
    print("\nLayer 2 - Weights:", w2)
    print("Layer 2 - Biases:", b2)
    print("\nLayer 3 - Weights:", w3)
    print("Layer 3 - Biases:", b3)
    print("\nOutput Layer - Weights:", w_out)
    print("Output Layer - Bias:", b_out)


In [7]:
initialize()

Neural Network Architecture:
Input layer: 5 nodes
Hidden layer 1: 3 nodes
Hidden layer 2: 2 nodes
Hidden layer 3: 3 nodes
Output layer: 1 node

Weights and Biases:
Layer 1 - Weights: [[ 0.10360069 -2.50727238 -1.52494524]
 [ 1.7183013   1.77676842  0.02085517]
 [ 0.51599234  1.51595689  0.91811867]
 [-0.1002834  -0.98557063  0.12253959]
 [ 0.24021476 -0.80513873  0.78229478]]
Layer 1 - Biases: [[-2.45883326 -1.50094332 -1.36082243]]

Layer 2 - Weights: [[-0.94146793 -1.36312967]
 [ 0.11627009 -0.47173855]
 [ 0.99041712  0.1916462 ]]
Layer 2 - Biases: [[-0.1650648   0.00635264]]

Layer 3 - Weights: [[ 0.55402648 -0.33407478  0.90044549]
 [-2.55475488 -0.77045299  1.62934602]]
Layer 3 - Biases: [[ 1.05887566  0.29988526 -1.77890686]]

Output Layer - Weights: [[ 1.27515021]
 [ 1.74890431]
 [-0.38792148]]
Output Layer - Bias: [[-2.20042743]]
