In [3]:
import numpy as np

In [4]:
def tanh(x):
    return np.tanh(x)

In [5]:
def initialize():
    inp = 5
    h1 = 3
    h2 = 2
    h3 = 2
    out = 1
    
    w1 = np.random.randn(inp,h1)
    b1 = np.zeros((1,h1))
    
    w2 = np.random.randn(h1,h2)
    b2 = np.zeros((1,h2))
    
    w3 = np.random.randn(h2,h3)
    b3 = np.zeros((1,h3))
    
    w_out = np.random.randn(h2,out)
    b_out = np.zeros((1,out))
   
    print("Neural Network Architecture:")
    print(f"Input layer: {inp} nodes")
    print(f"Hidden layer 1: {h1} nodes")
    print(f"Hidden layer 2: {h2} nodes")
    print(f"Hidden layer 3: {h3} nodes")
    print(f"Output layer: {out} node")
    print("\nWeights and Biases:")
    print("Layer 1 - Weights:", w1)
    print("Layer 1 - Biases:", b1)
    print("\nLayer 2 - Weights:", w2)
    print("Layer 2 - Biases:", b2)
    print("\nLayer 3 - Weights:", w3)
    print("Layer 3 - Biases:", b3)
    print("\nOutput Layer - Weights:", w_out)
    print("Output Layer - Bias:", b_out)
    
    # Compute activations for each node in the first hidden layer
    inp_lay = np.random.randn(1,inp)
    act_h1 = tanh(np.dot(inp_lay,w1) + b1)
    print("\nActivations in the First Hidden Layer:",act_h1)
    
    act_h2 = tanh(np.dot(act_h1,w2) + b2)
    print("\nActivations in the Second Hidden Layer:",act_h2)
    
    act_h3 = tanh(np.dot(act_h2,w3) + b3)
    print("\nActivations in the Third Hidden Layer:",act_h3)

In [6]:
initialize()

Neural Network Architecture:
Input layer: 5 nodes
Hidden layer 1: 3 nodes
Hidden layer 2: 2 nodes
Hidden layer 3: 2 nodes
Output layer: 1 node

Weights and Biases:
Layer 1 - Weights: [[-0.65233062  0.41739071  0.64932039]
 [ 0.03603011 -1.29546632 -0.06803138]
 [-1.53829651 -0.71232978 -0.49586421]
 [-0.06496751  1.01598549  0.57858562]
 [ 0.13704631  0.71962728 -0.67569677]]
Layer 1 - Biases: [[0. 0. 0.]]

Layer 2 - Weights: [[-0.14402589 -2.89146134]
 [-0.65887961  1.16207978]
 [ 0.6202981   1.57276385]]
Layer 2 - Biases: [[0. 0.]]

Layer 3 - Weights: [[ 0.06424776 -1.11496   ]
 [-0.54942504 -0.75130911]]
Layer 3 - Biases: [[0. 0.]]

Output Layer - Weights: [[ 0.67209357]
 [-0.38415309]]
Output Layer - Bias: [[0.]]

Activations in the First Hidden Layer: [[ 0.90121839  0.02514955 -0.97492055]]

Activations in the Second Hidden Layer: [[-0.63581109 -0.99946164]]

Activations in the Third Hidden Layer: [[0.46860383 0.89761541]]
