In [15]:
import numpy as np

In [16]:
def relu(x):
    return np.maximum(0,x)

In [19]:
def initialize():
    inp = 5
    h1 = 3
    h2 = 2
    h3 = 2
    out = 1
    
    w1 = np.random.randn(inp,h1)
    b1 = np.random.randn(1,h1)
    
    w2 = np.random.randn(h1,h2)
    b2 = np.random.randn(1,h2)
    
    w3 = np.random.randn(h2,h3)
    b3 = np.random.randn(1,h3)
    
    w_out = np.random.randn(h3,out)
    b_out = np.random.randn(1,out)
   
    print("Neural Network Architecture:")
    print(f"Input layer: {inp} nodes")
    print(f"Hidden layer 1: {h1} nodes")
    print(f"Hidden layer 2: {h2} nodes")
    print(f"Hidden layer 3: {h3} nodes")
    print(f"Output layer: {out} node")
    print("\nWeights and Biases:")
    print("Layer 1 - Weights:", w1)
    print("Layer 1 - Biases:", b1)
    print("\nLayer 2 - Weights:", w2)
    print("Layer 2 - Biases:", b2)
    print("\nLayer 3 - Weights:", w3)
    print("Layer 3 - Biases:", b3)
    print("\nOutput Layer - Weights:", w_out)
    print("Output Layer - Bias:", b_out)
    
    # Compute activations for each node in the first hidden layer
    inp_lay = np.random.randn(1,inp)
    act_h1 = relu(np.dot(inp_lay,w1) + b1)
    print("\nActivations in the First Hidden Layer:",act_h1)
    
    act_h2 = relu(np.dot(act_h1,w2) + b2)
    print("\nActivations in the Second Hidden Layer:",act_h2)
    
    act_h3 = relu(np.dot(act_h2,w3) + b3)
    print("\nActivations in the Third Hidden Layer:",act_h3)

In [20]:
initialize()

Neural Network Architecture:
Input layer: 5 nodes
Hidden layer 1: 3 nodes
Hidden layer 2: 2 nodes
Hidden layer 3: 2 nodes
Output layer: 1 node

Weights and Biases:
Layer 1 - Weights: [[-2.90975821 -0.24572622  0.131157  ]
 [ 0.74836216  0.75925032 -0.87883958]
 [ 1.00475444  0.61894424 -0.20599101]
 [ 0.3457995  -2.24879534 -0.86454721]
 [-0.04230852  0.41503229  1.0745564 ]]
Layer 1 - Biases: [[0.51634714 0.5827655  0.48825924]]

Layer 2 - Weights: [[-0.97695754 -1.03313125]
 [ 0.18407951 -1.00658248]
 [ 0.34069686 -0.45724586]]
Layer 2 - Biases: [[0.57134822 2.12771419]]

Layer 3 - Weights: [[ 2.32855219 -0.06548354]
 [ 0.06279861  0.47059225]]
Layer 3 - Biases: [[1.05388766 1.48173088]]

Output Layer - Weights: [[-0.50214487]
 [-2.03613296]]
Output Layer - Bias: [[0.95445417]]

Activations in the First Hidden Layer: [[1.69872316 9.92322786 4.24440895]]

Activations in the Second Hidden Layer: [[2.18448751 0.        ]]

Activations in the Third Hidden Layer: [[6.14058083 1.3386829 ]]